{{- if .Values.wallarm.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.wallarm.tarantool.service.annotations }}
  annotations: {{ toYaml .Values.wallarm.tarantool.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
    app.kubernetes.io/functional-component: controller
  {{- if .Values.wallarm.tarantool.service.labels }}
    {{- toYaml .Values.wallarm.tarantool.service.labels | nindent 4 }}
  {{- end }}
  name: {{ include "kong.fullname" . }}-wallarm-tarantool
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: tarantool
      port: {{ template "wallarm.tarantoolPort" . }}
      protocol: TCP
  selector:
    {{- include "kong.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/wallarm-component: {{ template "wallarm.tarantoolName" . }}
{{- end }}
